name: iso_mdoc
description: Library for handling datastructures described in ISO/IEC 18013-5.
version: 1.3.1
repository: https://github.com/b2cm/iso_mdoc
homepage: https://github.com/b2cm/iso_mdoc

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  cbor: ^6.2.0
  ed25519_edwards: ^0.3.1
  x25519: ^0.1.1
  pointycastle: ^3.7.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
